WIP - created 3 styled button components
iPlayed-games/frontend pull request #72
Opened 2023-08-25 22:35 UTC by anivm01

so far, I've made 3 styled button components 
![buttons-so-far](https://github.com/iPlayed-games/frontend/assets/109157075/c9a43fe5-c792-44b5-a2bb-644ea8e94c1a)
Issues: 
- I made a styled folder inside the components folder and put the button.ts inside it - is this the correct file structure?
- the MUI Button component has a strange ripple effect that can only be disabled through a prop - How do I target and disable that prop from the button.ts file rather than having to write it as a prop every time we use the button?
- I cleaned up and dry-ed the code as much as I could. Please look at it and let me know if there's more I could do
- I would like help converting the 3 styled components into variants instead as part of this ticket.

2023-08-29 17:00 UTC, sergiobtos requested changes

2023-08-29 17:00 UTC, sergiobtos commented on src/components/styled/Button.ts
can you please create a folder called src\common and move your to there with the index file to export them.

2023-08-29 17:00 UTC, sergiobtos commented on src/components/Header/Header.tsx
> +// import { Button } from '@mui/material'
delete code which is not been used.

2023-08-29 17:38 UTC, rmc3408 commented on src/components/styled/Button.ts
rename to something like `src/components/common/Button/index.tsx`

2023-08-29 17:41 UTC, rmc3408 reviewed
tiny changes but it looks good.
Sergio has the code to change styles of button based on props.

2023-08-29 17:41 UTC, rmc3408 commented on src/components/Header/Header.tsx
>  interface HeaderProps {}
Could you clean this.
remove interface and call Header as export default funtion Header

2023-08-29 17:41 UTC, rmc3408 commented
Link your PR to your ticket on development

2023-08-31 02:55 UTC, anivm01 commented on src/components/styled/Button.ts
I don't have an index file though. I'm just styling the existing button component from MUI. So I'm not really exporting anything. Should I be exporting something and if so what?

2023-08-31 03:00 UTC, anivm01 commented on src/components/Header/Header.tsx
>  interface HeaderProps {}
Okay. I did it in an arrow function the same as the footer
Is that okay?

2023-08-31 03:02 UTC, anivm01 commented on src/components/Header/Header.tsx
> +// import { Button } from '@mui/material'
Done!

2023-08-31 13:36 UTC, anivm01 commented on src/components/styled/Button.ts
I made the common folder and put a button folder inside and changed the file name to index. I am not sure if it should be .tsx though. It is like the style.ts files we have for other components. No tsx is being exported. There isn't even a default export since I'm exporting 3 different styled components. and the tsx is coming from MUI. Take a look and let me know if i should keep it as index or use style or styled instead maybe?

2023-08-31 14:47 UTC, rmc3408 approved these changes
LGTM

2023-08-31 14:49 UTC, rmc3408 approved these changes
LGTM

2023-08-31 15:35 UTC, sergiobtos approved these changes
LGTM.

2023-08-31 15:35 UTC, sergiobtos commented on src/components/Header/Header.tsx
>  interface HeaderProps {}
HeaderProps is not been used, can be deleted as well. follow this code here : export default function Home() {

2023-08-31 15:37 UTC, rmc3408 commented on src/components/Header/Header.tsx
>  interface HeaderProps {}
this doesnt exist anymore and she changed to export default. @anivm01 can resolve it

2023-08-31 15:38 UTC, merged